global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: ahsoka
    honor_timestamps: true
    scrape_interval: 15s
    #    oauth2:
    #      client_id: prometheus
    #      client_secret: qKbVRGFxY4fSs5kD2QJMmql2QvLSkRye
    #      token_url: http://custom_keycloak:8080/realms/FamilyBudget/protocol/openid-connect/token
    #      endpoint_params:
    #        grant_type: client_credentials
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - otel-collector:8889
