version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.7
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@55w0rd
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    network_mode: host
