version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.7
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=53nH@d3f@u1t4d@5IT
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - custom-keycloak

networks:
  custom-keycloak:
    name: custom-keycloak
    driver: bridge