version: "3.9"
services:
  keycloak:
    container_name: custom_keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=53nH@d3f@u1t4d@5IT
    ports:
      - "8080:8080"
    networks:
      - custom-keycloak
    command:
      - start

networks:
  custom-keycloak:
    name: custom-keycloak
    driver: bridge