services:
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: TRUE
    restart: always