version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_DB=keycloak
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    network_mode: "host"

  keycloak:
    container_name: custom_keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=P@55w0rd
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://127.0.0.1:5432/keycloak?user=postgres&password=P@55w0rd&sslmode=disable&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    network_mode: "host"
    command:
      - start-dev

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    network_mode: "host"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 9002:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=P@55w0rd
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    network_mode: "host" 

volumes:
  prom_data: