version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_DB=keycloak
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - custom-budget
      
  keycloak:
    container_name: custom_keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=P@55w0rd
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak?user=postgres&password=P@55w0rd&sslmode=disable&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    ports:
      - "8080:8080"
    networks:
      - custom-budget
    command:
      - start-dev
      
networks:
  custom-budget:
    name: custom-budget
    driver: bridge