version: "2"
services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: unless-stopped
    ports:
      - "9411:9411"
      
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
      
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8889:8889"   # Prometheus exporter metrics
      - "4318:4318"   # OTLP gRPC receiver
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - zipkin-all-in-one